### ISSUE TITLE
Update to nestjs/testing 7.5.5 due to vulnerability

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-api#27]
Dependabot and the npm alert about a high severity issue with the npm package "dicer". We should update to the newest version of nestjs/testing. But it introduces breaking changes so we might need to update some code.

npm audit:

![image](https://user-images.githubusercontent.com/14041976/170743654-81a4e92e-f4ab-4e25-a2a1-515e7d839a77.png)

**Comment by Saela** [comment]
@Tugark FYI

**Comment by Tugark** [comment]
@Saela I've seen that one, but you're suggesting a downgrade. We are using nest 8.x, so forcing the update will install a lower version and I am not sure that is the way to go. Besides, it is - if I remember right - just a dev dependency, so it is not present in deployed code.

It is also mentioned in https://github.com/nestjs/nest/issues/9655. I would wait until they officialy upgrade it themselves.

**Comment by Saela** [comment]
@Tugark Yes as it is only a dev dependency we can wait. Otherwise I would have downgraded (as this is an ok way to go if there is a security issue. Unless it introduces a lot of breaking changes of course). I'll close this issue.
