### ISSUE TITLE
Add image upload

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-api#35]
Add simple image upload (without gps data)

# Review

- [x] Code is written
- [x] Tests (if necessary) are written
- [x] Code is documented (either in documentation itself or in code)
- [ ] Code is reviewed
- [x] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [x] Build is successful (including all tests passed)
- [x] Deployment to staging works
- [ ] Manual testing on staging by peer

**Comment by Tugark** [comment]
@Saela I added some notes to the documentation in https://github.com/gipfeli-io/documentation/commit/39f834a8dc3842b0618ca2d81c218ac2af746e63, but I have to adjust the UML diagrams as well.
