### ISSUE TITLE
[BUG]: Creating a tour with validation errors still returns success

### ISSUE THREAD

**Issue by Tugark** [gipfeli-io/gipfeli-api#53]
### Description of the bug

If I create a tour and leave out e.g. the title, the backend error is triggered but we are still redirected to the tour list.

Another error is when the backend throws a 500 error, the tour is successfully added - I guess in the local database.

I believe that has to do with the offline functionality, no?

### Steps To Reproduce

1. Create a tour and leave out some fields, submit

Or:

1. create a tour and throw a db error

**Comment by Saela** [comment]
needs re-testing because we updated the error handling and the offline functionality.
