### ISSUE TITLE
Add gpx file upload

### ISSUE THREAD

**Issue by Saela** [gipfeli-io/gipfeli-api#68]
- Add new endpoint to upload gpx file
- Extend image upload to also handle gpx files and upload it to the already existing bucket (create new folder for this). 
- Add new endpoint to return gpx file

# Review

- [x] Code is written
- [x] Tests (if necessary) are written
- [ ] Code is documented (either in documentation itself or in code)
- [x] Code is reviewed
- [x] Must implement functionality specified in the ticket and in line with the design specifications (e.g. wireframes)
- [x] Build is successful (including all tests passed)
- [x] Deployment to staging works
- [x] Manual testing on staging by peer

**Comment by Tugark** [comment]
@Saela See https://github.com/gipfeli-io/gipfeli-api/issues/76
