### ISSUE TITLE
[BUG]: Check Foreign Relations

### ISSUE THREAD

**Issue by Tugark** [gipfeli-io/gipfeli-api#80]
### Description of the bug

Not sure if the relations are correctly set up.

Currently, I cannot delete a GPX object if it is assigned to a tour. Do we want this? Otherwise, I guess we'd have to move `cascade: true` to the GpxFile and not the Tour?

### Steps To Reproduce

.

**Comment by Saela** [comment]
We decided to leave it like this as it only influences the way we can delete a gpx file entry in the database using sql.
